# training
conf_id: snowpole_plain_030923
algorithm: Plain
num_iters: 30000
log_interval: 10
parallel: 0

# data
# will need to update with GPU settings
dataset_root: /Users/catherinebreen/Chapter1/segmentationModel/
dataset_name: SNOWPOLES
num_classes: 2 #
batch_size: 1 # will update with GPU
num_workers: 64

# model
model_name: DeepLabV3_ResNet50
num_layers: 50
output_stride: 16
weights_init: ImageNet

# optim
## feature
lr_feature: 0.001
momentum_feature: 0.9
weight_decay_feature: 0.0004
## classifier
lr_classifier: 0.01
momentum_classifier: 0.9
weight_decay_classifier: 0.0004
## lr_scheduler
step_size: 10000
gamma: 0.1
